# Install Ruby and rvm - Ruby Version Manager
language: ruby
rvm:
- 2.6.3

# Install Jekyll
install:
  - gem install jekyll
  - gem install jekyll-theme-hydure
  - gem install addressable

# Build Jekyll blog
script:
  - jekyll build

# Upload Jekyll blog files to Amazon S3 bucket
deploy:
  on:
    branch: master
  provider: s3
  bucket: mann.gdn 
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: eu-west-2
  acl: public_read
  skip_cleanup: true
  local_dir: ./_site
